import { recommendations } from "@/data/recommendations";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, ArrowRight, AlertTriangle, Info, Clock, CheckCircle2 } from "lucide-react";
import { motion } from "framer-motion";

export default function Recommendations() {
  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  };

  const getPriorityConfig = (priority: string) => {
    switch (priority) {
      case "HIGH":
        return { 
          color: "bg-red-100 text-red-800 border-red-200 dark:bg-red-900/30 dark:text-red-400", 
          icon: <AlertTriangle className="h-4 w-4 mr-1" />
        };
      case "MEDIUM":
        return { 
          color: "bg-amber-100 text-amber-800 border-amber-200 dark:bg-amber-900/30 dark:text-amber-400", 
          icon: <Clock className="h-4 w-4 mr-1" />
        };
      case "LOW":
        return { 
          color: "bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400", 
          icon: <Info className="h-4 w-4 mr-1" />
        };
      default:
        return { color: "bg-gray-100 text-gray-800", icon: null };
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="h-12 w-12 bg-primary/10 text-primary rounded-xl flex items-center justify-center">
          <Sparkles className="h-6 w-6" />
        </div>
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">AI Action Recommendations</h1>
          <p className="text-muted-foreground">Prioritized, data-driven action items based on employee feedback analysis.</p>
        </div>
      </div>

      <motion.div variants={container} initial="hidden" animate="show" className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {recommendations.map((rec) => {
          const config = getPriorityConfig(rec.priority);
          return (
            <motion.div key={rec.id} variants={item} className="h-full">
              <Card className="h-full flex flex-col hover:shadow-md transition-shadow relative overflow-hidden group">
                <div className={`absolute top-0 left-0 w-1 h-full ${rec.priority === 'HIGH' ? 'bg-red-500' : rec.priority === 'MEDIUM' ? 'bg-amber-500' : 'bg-emerald-500'}`}></div>
                <CardHeader className="pb-3 pt-6 px-6">
                  <div className="flex justify-between items-start mb-2">
                    <Badge variant="outline" className={`${config.color} font-bold px-2 py-0.5 border`}>
                      {config.icon} {rec.priority} PRIORITY
                    </Badge>
                    <div className="text-xs font-medium text-muted-foreground flex items-center bg-muted px-2 py-1 rounded-md">
                      Impact: {rec.impact}%
                    </div>
                  </div>
                  <CardTitle className="text-lg leading-tight group-hover:text-primary transition-colors">{rec.title}</CardTitle>
                </CardHeader>
                <CardContent className="flex-1 px-6">
                  <p className="text-sm text-muted-foreground leading-relaxed">{rec.description}</p>
                  <div className="mt-4 flex items-center gap-2 text-xs font-medium text-foreground/80">
                    <span className="text-muted-foreground">Target Dept:</span> 
                    <Badge variant="secondary" className="font-normal">{rec.department}</Badge>
                  </div>
                </CardContent>
                <CardFooter className="px-6 pb-6 pt-0 mt-auto">
                  <Button variant="outline" className="w-full justify-between hover:bg-primary hover:text-primary-foreground">
                    Create Action Plan
                    <ArrowRight className="h-4 w-4" />
                  </Button>
                </CardFooter>
              </Card>
            </motion.div>
          );
        })}
      </motion.div>

      <Card className="mt-8 bg-sidebar text-sidebar-foreground border-sidebar-border">
        <CardContent className="p-6 flex items-start gap-4">
          <CheckCircle2 className="h-6 w-6 text-emerald-500 shrink-0 mt-0.5" />
          <div>
            <h3 className="text-lg font-semibold mb-1">Recommendation Methodology</h3>
            <p className="text-sidebar-foreground/70 text-sm leading-relaxed">
              These recommendations are generated by analyzing the gap between expected and actual scores across all 15 survey dimensions. Priority is assigned based on the frequency of mention in qualitative feedback (suggestions/improvements) combined with critically low quantitative scores (&lt; 3.0) in related survey questions.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
